apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: mini-render-backend:local
          imagePullPolicy: Never
          command: ["rq"]
          args: ["worker", "deployments", "--worker-class", "rq.SimpleWorker"]
          env:
            - name: DATABASE_URL
              value: postgresql://sahil:password123@postgres:5432/minirender
            - name: REDIS_URL
              value: redis://redis:6379/0